config/routes.rb
Rails.application.routes.draw do

  root "rooms#index"
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'
  get    '/signup',    to: 'users#new'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :rooms do
    resources :reservations,        only: [:create]
  end

  post 'messages/send_custom_message', to: 'messages#send_custom_message', as: 'message'

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :reservations, dependent: :destroy
  has_many :users, through: :reservations
  has_many :images

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :logged_in_user

  def index
    if current_user.admin?
      admin_dashboard
    else  # For when user is a customer
      customer_dashboard
    end
  end

  def show
    @room = Room.find(params[:id])
    @reservation = @room.reservations.build
  end

  private

    def admin_dashboard
      sql = "check_in_at <= ? AND check_out_at > ?"
      # default list (for available rooms today)
      @rooms = Room.distinct.left_outer_joins(:reservations).where.not(sql,
                            Date.today, Date.today).or(
                            Room.distinct.where.missing(:reservations)).order(:number)
      # List of booked rooms today
      if params[:status] && params[:status] == 'booked'
        @rooms = Room.joins(:reservations).where(sql, Date.today, Date.today)
      end
      render role_home_template
    end

    def customer_dashboard
      @rooms = Room.all
      # Date range filter
      if params[:date_from].present? && params[:date_to].present?
        # Get any overlaps
        sql = ":date_to >= check_in_at AND check_out_at > :date_from"
        # Get rooms where no overlap exists in reservations + rooms with no reservations yet
        @rooms = @rooms.distinct.left_outer_joins(:reservations).where.not(sql,
              date_to: params[:date_to], date_from: params[:date_from]).or(Room.distinct.where.missing(:reservations)).order(:number)
      end
      # Price filter
      if params[:price_from].present? && params[:price_to].present?
        @rooms = @rooms.where("price_per_day >= ? AND price_per_day <= ?", params[:price_from], params[:price_to]).order(:number)
      end
      @rooms
      render role_home_template
    end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/admin_dash.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>Admin dashboard for <%= current_user.name %></h1>
    <div class="message-form">
      <%= form_with(url: message_path,
                    local: true) do |form| %>
        <%= form.label :message, "Send a message to all users currently in the hotel" %>
        <%= form.text_field :message, class: 'form-control' %>

        <%= form.submit "Send", class: 'btn btn-primary' %>
      <% end %>
    </div>
    <div class="rooms-status">
      <%= link_to "Available rooms today", rooms_path(status: :available),
            class: active_class(rooms_path(status: :available), root_path, rooms_path) %>

      <%= link_to "Booked rooms today", rooms_path(status: :booked),
            class: active_class(rooms_path(status: :booked)) %>
    </div>
    <div class="rooms-list">
      <ul>
        <% @rooms.each do |room| %>
          <li>
            <div class="room-name">
              #<%= room.number %> - <%= room.name %>
            </div>
            <div class="room-description">
              <%= room.description %>
            </div>
            <div class="room-price">
              Price per day: <%= room.price_per_day %> &euro;
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/rooms/customer_dash.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>Customer dashboard for <%= current_user.name %></h1>

    <%= form_with(url: rooms_path, method: :get, html: { autocomplete: "off" }, class: "rooms-filter-form") do |form| %>

      <div class="rooms-filter">
        <div class="price-filter">
          <h3>Filter by price</h3>
          <div>
            <%= form.label :price_from, "from:" %>
            <%= form.number_field :price_from, step: 1, min: 0, class: 'form-control', value: params[:price_from] %>

            <%= form.label :price_to, "to:" %>
            <%= form.number_field :price_to, step: 1, min: 0, class: 'form-control', value: params[:price_to] %>
          </div>
        </div>
        <div class="date-filter">
          <h3>Filter by availability</h3>
          <div>
            <%= form.label :date_from, "from:" %>
            <%= form.date_field :date_from, class: "form-control", min: Date.today, value: params[:date_from] %>

            <%= form.label :date_to, "to:" %>
            <%= form.date_field :date_to, class: "form-control", min: Date.today, value: params[:date_to] %>
          </div>
        </div>
      </div>
      <%= form.submit "Apply filters", name: nil, class: 'btn btn-primary' %>
      <%= link_to "Reset filters", rooms_path(price_from: '', price_to: '', date_from: '', date_to: ''),
                                   class: 'btn btn-primary' %>

    <% end %>
    <div class="rooms-list">
      <ul class="customer-list">
        <% @rooms.each do |room| %>
          <li>
            <%= link_to room do %>
              <div class="room-name">
                #<%= room.number %> - <%= room.name %>
              </div>
              <div class="room-description">
                <%= room.description %>
              </div>
              <div class="room-price">
                Price per day: <%= room.price_per_day %> &euro;
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="room-name">
      <h1>#<%= @room.number %> - <%= @room.name %></h1>
    </div>
    <div class="room-images">
      <% @room.images.each do |image| %>
        <%= image_tag image.url %>
      <% end %>
    </div>
    <div class="room-description">
      <%= @room.description %>
    </div>
    <div class="room-price">
      Price per day: <strong><%= @room.price_per_day %> &euro;</strong>
    </div>
    <div class="room-reservations">
      <%= form_with(model: @reservation,
                    url: [@room, @reservation],
                    local: true) do |form| %>
        <h3>Booking</h3>
          <%= render 'shared/error_messages', object: form.object %>
          <div>
            <%= form.label :check_in_at, "Check in at:" %>
            <%= form.date_field :check_in_at, class: "form-control", min: Date.today %>

            <%= form.label :check_out_at, "Check out at:" %>
            <%= form.date_field :check_out_at, class: "form-control", min: Date.today %>

            <%= form.submit "Make reservation", name: nil, class: 'btn btn-primary' %>
          </div>
        <% end %>
    </div>
  </div>
</div>