config/routes.rb
Rails.application.routes.draw do

  root "rooms#index"
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'
  get    '/signup',    to: 'users#new'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :rooms do
    resources :reservations,        only: [:create]
  end

  post 'messages/send_custom_message', to: 'messages#send_custom_message', as: 'message'

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <%= link_to "Kodius task", root_path, id: "logo" %>
  <% if logged_in? %>
    <div class="user-options">
      <%= link_to "edit info", edit_user_path(current_user), id: "edit-user-info" %>
      <%= link_to "delete account", current_user, data: {
                                          "turbo-method": :delete,
                                          "turbo-confirm": "Are you sure?" },
                                          id: "delete-user-link" %>
      <%= link_to "Log out", logout_path, data: { "turbo-method": :delete },
                                          id: "logout-link" %>
    </div>
  <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Kodius task</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "layout", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_importmap_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      
      <%= yield %>

      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>